### ISSUE TITLE
Tooltip not working with AutoResizer

### ISSUE THREAD

**Issue by Frekansapp** [Autodesk/react-base-table#75]
React-Texty Tooltip not working with AutoResizer

**Comment by nihgwu** [comment]
Could you provide more information? Thanks

**Comment by Frekansapp** [comment]
if I don't use autoresizer it works
```
import Text from 'react-texty'
import 'react-texty/styles.css'

const TableCell = ({ className, cellData }) => (
    <Text className={className} >{cellData}</Text>
)

const TableHeaderCell = ({ className, column }) => (
  <Text className={className}>{column.title}</Text>
)

  <div
        style={{
          width: '100%',
          position: 'relative',
          margin: 0,
          padding: 0,
          height: (window.innerHeight - 135)
        }} >
      
        <AutoResizer>
          {({ width, height }) => (
        
              <BaseTable
                fixed
                //classPrefix="AdvanceTable"
                rowClassName={this._rowClassName}
                width={(width)}
                data={data}
                height={(height - 49)}
                columns={constructionInputs}
                disabled={loading}
                loadingMore={loadingMore}
                onEndReachedThreshold={300}
                onEndReached={this.handleEndReached}
                overlayRenderer={this.renderOverlay}
                emptyRenderer={this.renderEmpty}
                components={{ TableCell, TableHeaderCell }}
                footerHeight={30}
                footerRenderer={this.renderTableFooter(width)}
                rowEventHandlers={{
                  onClick: (data) => this.onRowClick(data),
                  onDoubleClick: (data) => this.onRowDoubleClick(data)
                }}
              />
         
          )}
        </AutoResizer>
      </div>
```

**Comment by nihgwu** [comment]
I can't find any issues with `AutoResizer` https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBAKgUwB6wLwwEoIIbColATwChRJZQAbAVwFtIZ0BzBMBAJ2ygQGEQb6EABQBGAAwBKUuGgwAJl2yMYLNp24ARRUKp1IAGhgAmMZOLTyMPmCjYAlmuXRClBHIB0cuwDcABsRgYAHc7OSgACwAuGGBsSmBRU28gmABaGAB2UwAHJAkAbgCYcIQ7JnCoaIBWMW9wwv8LWQAJBzQYZ1cPLz8igDNwKFSIOwAvBGiRADZcwsCBm1Sg0vLKzNM5mP4QdmiAYgBmA6mpgE5TzdpsdiYHVIAjECgoEFpJsVniRrJZOGx71w8BCUSjKIQAbxilGwEAgADlsLQEIZgMDKFpbDAAL4SRgAPhgQiKAB4CBRobCEUjUODgBT4YiEFi8bS0RjsFjiQB6Ml44hSJqwP4AhDNHByDhAkFgyF0mEMpEo-h6bG41AEomBUnIcnyqkIGlyymM5m05X0dxQOxQVycnk6vkC5DZHawCV9bDUSiwIRqjUkvmBLWtGx4rAjcYwQggajsGD3dggIIQDgwbBgOQdBAIbkhqCBoPE6y2BwcAtBmDEgCC1Be4bGZaKFcC4IhwVCEUMJTKFVV+MJTebWoAQjCEMLXIOh4EQmFwjTZxEsVPp93VjS1xVl9Pm7pBIbzZBtzugwpbDSzxyV0PQLQXWwbBAaZCJ7w0YZX2LsBL2FLQVjjx3Lly2bCRAMLLkazrBAI0bCtuWLew1ALblHWIIA

**Comment by Frekansapp** [comment]
@nihgwu i found the problem if i use like this there is no problem
const Container = styled.div`
  width: calc(100vw - 700px);
  height: 50vh;
`
but if i use like this Tooltip not working

const Container = styled.div`
  width: **'100%'**;
  height: 50vh;
`
i should use relative div with dynamic width how can i use it without causing problem

**Comment by nihgwu** [comment]
Sorry I'm not sure what you are talking about, if you think it's still an issue, could you provide a reproducable playground so I can understand your problem better, thanks

**Comment by nihgwu** [comment]
@Frekansapp Hi, there is an internal bug reported today which would be related to your problem, but I think it's `react-texty`'s problem, so I'd like to continue the topic there https://github.com/nihgwu/react-texty/issues/1

**Comment by nihgwu** [comment]
@Frekansapp this issue should be fixed with latest version of `react-texty`

**Comment by Frekansapp** [comment]
@nihgwu thanks, I will try it asap.

**Comment by Frekansapp** [comment]
@nihgwu No this isn't solved my problem. I will open new issue with detailed explanation later.

**Comment by nihgwu** [comment]
@Frekansapp thanks
